// <auto-generated />
namespace Billboard.Models.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Pricing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pricing));
        
        string IMigrationMetadata.Id
        {
            get { return "201403301149116_Pricing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
